#pragma kernel CSMain

RWTexture2D<float4> Source;
RWTexture2D<float4> Destination;

float4x4 _CameraToWorld;
float4x4 _CameraInverseProjection;
float3 _LightDirection;

float power;
float darkness;
float blackAndWhite;
float brightness;
float transparencyAmount;
float4 colourAMix;
float4 colourBMix;
float maxDst;
float alpha;
float totalAlpha;
float fractalScale;

int maxStepCount;
int maxIterations;
float angle;
float3 positionOffset;
float3 fractalRotation;
float perspectiveCorrection;

static const float epsilon = 0.001f;

struct Ray
{
    float3 origin;
    float3 direction;
};

Ray CreateRay(float3 origin, float3 direction)
{
    Ray ray;
    ray.origin = origin;
    ray.direction = direction;
    return ray;
}

Ray CreateCameraRay(float2 uv)
{
    float3 origin = mul(_CameraToWorld, float4(0, 0, 0, 1)).xyz;
    float3 destination = mul(_CameraInverseProjection, float4(uv, 0, 1)).xyz;
    destination = mul(_CameraToWorld, float4(destination, 1)).xyz;
    float3 direction = normalize(destination - origin);
    return CreateRay(origin, direction);
}

float3x3 RotationMatrix(float3 rotation)
{
    float3 rad = rotation * 0.017453292;
    float cx = cos(rad.x);
    float sx = sin(rad.x);
    float cy = cos(rad.y);
    float sy = sin(rad.y);
    float cz = cos(rad.z);
    float sz = sin(rad.z);
    
    float3x3 rotX = float3x3(
        1, 0, 0,
        0, cx, -sx,
        0, sx, cx
    );
    
    float3x3 rotY = float3x3(
        cy, 0, sy,
        0, 1, 0,
        -sy, 0, cy
    );
    
    float3x3 rotZ = float3x3(
        cz, -sz, 0,
        sz, cz, 0,
        0, 0, 1
    );
    
    return mul(mul(rotZ, rotY), rotX);
}

float2 SceneInfo(float3 position)
{
    float3 localPos = position - positionOffset;
    
    float3x3 rotMatrix = RotationMatrix(-fractalRotation);
    localPos = mul(rotMatrix, localPos);
    
    localPos /= fractalScale;
    float3 z = localPos;
    float dr = 1.0;
    float r = 0.0;
    int iterations = 0;

    for (int i = 0; i < maxIterations; i++)
    {
        iterations = i;
        r = length(z);

        if (r > 2)
        {
            break;
        }

        float theta = acos(z.z / r);
        float phi = atan2(z.y, z.x);
        dr = pow(r, power - 1.0) * power * dr + 1.0;

        float zr = pow(r, power);
        theta = theta * power;
        phi = phi * power;

        z = zr * float3(sin(theta) * cos(phi), sin(phi) * sin(theta), cos(theta));
        z += localPos;
    }

    float dst = 0.5 * log(r) * r / dr;
    dst = max(dst * fractalScale * 0.99, 0.0001);
    return float2(iterations, dst);
}

float3 EstimateNormal(float3 p)
{
    float x = SceneInfo(float3(p.x + epsilon, p.y, p.z)).y - SceneInfo(float3(p.x - epsilon, p.y, p.z)).y;
    float y = SceneInfo(float3(p.x, p.y + epsilon, p.z)).y - SceneInfo(float3(p.x, p.y - epsilon, p.z)).y;
    float z = SceneInfo(float3(p.x, p.y, p.z + epsilon)).y - SceneInfo(float3(p.x, p.y, p.z - epsilon)).y;
    return normalize(float3(x, y, z));
}

struct minStruct
{
    uint xMin;
    uint yMin;
    float dMin;
};

RWStructuredBuffer<minStruct> GroupMinBuffer;
groupshared minStruct rowMinData[64];

[numthreads(64, 1, 1)]
void CSMain(uint3 groupID : SV_GroupID, uint3 groupThreadID : SV_GroupThreadID, uint groupIndex : SV_GroupIndex, uint3 id : SV_DispatchThreadID)
{
    uint width, height;
    Destination.GetDimensions(width, height);

    float2 uv = id.xy / float2(width, height);

    float4 result = float4(1, 1, 1, alpha);
    
    Ray ray = CreateCameraRay(uv * 2 - 1);
    float rayDst = 0;
    int marchSteps = 0;

    while (rayDst < maxDst && marchSteps < maxStepCount)
    {
        marchSteps++;
        float2 sceneInfo = SceneInfo(ray.origin);
        float dst = sceneInfo.y;

        if (dst <= epsilon * rayDst * 0.5)
        {
            float escapeIterations = sceneInfo.x;
            float3 normal = EstimateNormal(ray.origin - ray.direction * epsilon * 3);
            //float3 normal = EstimateNormal(ray.origin - ray.direction * epsilon * 2);

            float colourA = saturate(dot(normal * 0.5 + 0.5, -_LightDirection));
            float colourB = escapeIterations / 16.0;
            float3 colourMix = saturate(colourA * colourAMix.xyz + colourB * colourBMix.xyz);
            //float3 colourMix = lerp(colourA  * colourAMix.xyz, colourB * colourBMix.xyz, colourA);
            
            result.xyz = colourMix.xyz;
            //result = 1- clamp(smoothstep(0, .8, colourB), 0, 1);
            result.a = lerp(colourBMix.a, colourAMix.a, 1 - clamp(smoothstep(0, .7, colourB), 0, 1));
            //result = colourBMix;
            break;
        }

        dst = min(dst, 0.1);
        
        ray.origin += ray.direction * dst;
        rayDst += dst;
    }

    float rim = marchSteps / darkness;
    float4 dest = lerp(float4(result.xyz, 0), result, blackAndWhite * rim);
    Destination[id.xy] = dest;

    rowMinData[groupIndex].xMin = 0;
    rowMinData[groupIndex].yMin = id.x;
    rowMinData[groupIndex].dMin = maxDst;
    if (rayDst < rowMinData[groupIndex].dMin)
    {
        rowMinData[groupIndex].xMin = id.y;
        rowMinData[groupIndex].dMin = rayDst;
    }

    GroupMemoryBarrierWithGroupSync();
    if (0 == (groupIndex & 1))
    {
        if (rowMinData[groupIndex + 1].dMin < rowMinData[groupIndex].dMin)
        {
            rowMinData[groupIndex] = rowMinData[groupIndex + 1];
        }
    }
    GroupMemoryBarrierWithGroupSync();
    if (0 == (groupIndex & 3))
    {
        if (rowMinData[groupIndex + 2].dMin < rowMinData[groupIndex].dMin)
        {
            rowMinData[groupIndex] = rowMinData[groupIndex + 2];
        }
    }
    GroupMemoryBarrierWithGroupSync();
    if (0 == (groupIndex & 7))
    {
        if (rowMinData[groupIndex + 4].dMin < rowMinData[groupIndex].dMin)
        {
            rowMinData[groupIndex] = rowMinData[groupIndex + 4];
        }
    }
    GroupMemoryBarrierWithGroupSync();
    if (0 == (groupIndex & 15))
    {
        if (rowMinData[groupIndex + 8].dMin < rowMinData[groupIndex].dMin)
        {
            rowMinData[groupIndex] = rowMinData[groupIndex + 8];
        }
    }
    GroupMemoryBarrierWithGroupSync();
    if (0 == (groupIndex & 31))
    {
        if (rowMinData[groupIndex + 16].dMin < rowMinData[groupIndex].dMin)
        {
            rowMinData[groupIndex] = rowMinData[groupIndex + 16];
        }
    }
    GroupMemoryBarrierWithGroupSync();
    if (0 == (groupIndex & 63))
    {
        if (rowMinData[groupIndex + 32].dMin < rowMinData[groupIndex].dMin)
        {
            rowMinData[groupIndex] = rowMinData[groupIndex + 32];
        }

        GroupMinBuffer[groupID.x] = rowMinData[groupIndex];
    }
}