name: Notify Discord on push

on:
  push:
    branches:
      - main  # change si besoin

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Build message
        id: msg
        run: |
          COMMITS_JSON=$(jq -n --arg ref "${{ github.ref_name }}" \
                               --arg repo "${{ github.repository }}" \
                               --arg pusher "${{ github.actor }}" \
                               --arg url  "https://github.com/${{ github.repository }}/commit/${{ github.sha }}" \
                               --arg msg  "${{ github.event.head_commit.message }}" \
                               '{
                                  content:
                                    "**[$repo]** push sur **$ref** par **$pusher**\n" +
                                    "Dernier commit:\n> $msg\n$url"
                                }')
          echo "payload=$COMMITS_JSON" >> $GITHUB_OUTPUT
      - name: Send to Discord
        run: |
          curl -sS -H "Content-Type: application/json" \
               -d '${{ steps.msg.outputs.payload }}' \
               "${{ secrets.DISCORD_WEBHOOK_URL }}"
